import { StrictMode } from "react";
import { AppProvider } from "./context/AppProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StrictMode>
        <AppProvider>
          <body className="bg-blue-500">{children}</body>
        </AppProvider>
      </StrictMode>
    </html>
  );
}
